name: Metrics
on:
  # Schedule updates (each hour)
  # schedule: [{cron: "0 * * * *"}]
  schedule: [{ cron: "0 */6 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
                  # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          filename: metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: "metadata"
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 3

      - name: Personal projects
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.projects.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: lowlighter
          base: ""
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
          plugin_projects_limit: 0
          config_timezone: Europe/Paris
      - name: 📅 Isometric commit calendar
        category: github
        description: |
          This plugin displays an isometric view of a user commit calendar along with a few additional statistics like current streak and average number of commit per day.
        examples:
          +full year calendar: https://github.com/lowlighter/metrics/blob/examples/metrics.plugin.isocalendar.fullyear.svg
          half year calendar: https://github.com/lowlighter/metrics/blob/examples/metrics.plugin.isocalendar.svg
        index: 0
        supports:
          - user
        scopes:
          - public_access
        inputs:
        
          plugin_isocalendar:
            description: |
              Enable isocalendar plugin
            type: boolean
            default: no
        
          plugin_isocalendar_duration:
            description: |
              Time range
        
              - half-year: 180 days
              - full-year: 1 year
            type: string
            default: half-year
            values:
              - half-year
              - full-year