name: GitHub metrics
on:
  schedule: [{ cron: "0 */12 * * *" }]
  push:
    branches: "main"
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          # plugin_music: yes
          # plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          # plugin_music_limit: 2
          plugin_isocalendar: yes
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          # plugin_languages_skipped: lowlighter
          # plugins_errors_fatal: yes
          config_timezone: Europe/Paris
          
      - name: Personal metrics (additional)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: "metadata"
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 3

      - name: Personal projects
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.projects.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: akir0
          base: ""
          plugin_projects: no
          plugin_projects_repositories: akir0/metrics/projects/1
          plugin_projects_limit: 0
          config_timezone: Europe/Paris
      - name: 📅 Isometric commit calendar
        category: github
        description: |
          This plugin displays an isometric view of a user commit calendar along with a few additional statistics like current streak and average number of commit per day.
        examples:
          +full year calendar: https://github.com/lowlighter/metrics/blob/examples/metrics.plugin.isocalendar.fullyear.svg
          half year calendar: https://github.com/lowlighter/metrics/blob/examples/metrics.plugin.isocalendar.svg
        index: 0
        supports:
          - user
        scopes:
          - public_access
        inputs:
        
          plugin_isocalendar:
            description: |
              Enable isocalendar plugin
            type: boolean
            default: no
        
          plugin_isocalendar_duration:
            description: |
              Time range
        
              - `half-year`: 180 days
              - `full-year`: 1 year
            type: string
            default: half-year
            values:
              - half-year
              - full-year
