name: GitHub metrics
on:
  # Schedule updates (each hour)
  # schedule: [{cron: "0 * * * *"}]
  schedule: [{ cron: "0 */6 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          # plugin_music: yes
          # plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
          # plugin_music_limit: 2
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          # plugin_languages_skipped: lowlighter
          # plugins_errors_fatal: yes
          config_timezone: Europe/Paris

      - name: Personal metrics (additional)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: "metadata"
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 3

      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year